In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, Input

x = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [1,0,0],[0,1,1],[1,0,1],[1,1,0],[1,1,1]])
y = np.array([0,1,1,1,0,0,0,1])
model = tf.keras.Sequential([
    Input(shape=(3,)),
    layers.Dense(4, activation="tanh"),
    layers.Dense(1, activation="sigmoid")
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.05), loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(x, y, epochs=100, verbose=0)
loss, accuracy = model.evaluate(x, y)
print("loss: ", loss)
print("accuracy: ",accuracy)
prediction = model.predict(x)
for inp, pred in zip(x, prediction):
    print(inp, round(pred[0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 1.0000 - loss: 0.0194
loss:  0.01942768692970276
accuracy:  1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
[0 0 0] 0
[0 0 1] 1
[0 1 0] 1
[1 0 0] 1
[0 1 1] 0
[1 0 1] 0
[1 1 0] 0
[1 1 1] 1
